# Generated by Django 5.2.8 on 2025-12-02 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=255, verbose_name='Descripción de la Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de Editorial')),
                ('telefono', models.CharField(max_length=40, verbose_name='Teléfono de Contacto')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email de Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Tienda')),
                ('lugar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Tienda/Sucursal',
                'verbose_name_plural': 'Tiendas/Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Título')),
                ('autor', models.CharField(max_length=40, verbose_name='Autor')),
                ('ilustrador', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ilustrador')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Adquisición')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('sinopsis', models.TextField(blank=True, null=True, verbose_name='Sinópsis del Libro')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_ventas.editorial', verbose_name='Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_ventas.tienda', verbose_name='Tienda Asignada')),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Venta')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada y Procesada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Venta')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_ventas.cliente', verbose_name='Cliente')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario_ventas.staff', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario Vendido')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Registro')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_ventas.libro', verbose_name='Libro Vendido')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad en Stock')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_ventas.bodega', verbose_name='Bodega')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_ventas.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'unique_together': {('libro', 'bodega')},
            },
        ),
    ]
